name: auth
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  get: ^4.6.5
  get_it: ^7.2.0
  flutter_svg: ^2.0.10
  form_field_validator: ^1.1.0
  image_picker: ^1.1.2 #By Flutter.Dev use MediaStore Api , safe for playStore
  flutter_contacts: ^1.1.9+2
  web_socket_channel: ^3.0.1 #By dart.dev team
  video_player: ^2.9.2 #By Flutter.dev
  url_launcher: ^6.3.1
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  restart_app: ^1.3.2 # Need after logout, login session expire
  leak_tracker: ^10.0.5 #by dart team for detect memory leak
  shimmer: ^2.0.0
  flutter_exit_app: ^1.1.4
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  open_filex: ^4.6.0
  popover: ^0.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
